name: Deploy develop branch

on:
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Deploy develop branch
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_SSH_ID }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            cd /home/ubuntu/develop_BE
            sudo git pull origin develop
            sudo pm2 restart server.js
